#!/bin/sh
set -ex

FREETYPE_VERSION="2.9"
HARFBUZZ_VERSION="1.7.6"
FRIBIDI_VERSION="1.0.2"
LIBASS_VERSION="0.14.0"
FFMPEG_VERSION="3.4.2"
MPV_VERSION="0.27.2"
UCHARDET_VERSION="0.0.6"

FREETYPE_URL="https://sourceforge.net/projects/freetype/files/freetype2/$FREETYPE_VERSION/freetype-$FREETYPE_VERSION.tar.bz2"
HARFBUZZ_URL="https://www.freedesktop.org/software/harfbuzz/release/harfbuzz-$HARFBUZZ_VERSION.tar.bz2"
FRIBIDI_URL="https://github.com/fribidi/fribidi/releases/download/v$FRIBIDI_VERSION/fribidi-$FRIBIDI_VERSION.tar.bz2"
LIBASS_URL="https://github.com/libass/libass/releases/download/$LIBASS_VERSION/libass-$LIBASS_VERSION.tar.gz"
FFMPEG_URL="http://www.ffmpeg.org/releases/ffmpeg-$FFMPEG_VERSION.tar.bz2"
MPV_URL="https://github.com/mpv-player/mpv/archive/v$MPV_VERSION.tar.gz"
UCHARDET_URL="https://www.freedesktop.org/software/uchardet/releases/uchardet-$UCHARDET_VERSION.tar.xz"

mkdir tarballs src
for URL in $UCHARDET_URL $FREETYPE_URL $HARFBUZZ_URL $FRIBIDI_URL $LIBASS_URL $FFMPEG_URL $MPV_URL; do
	TARNAME=${URL##*/}
	curl -f -L -- $URL > tarballs/$TARNAME
	tar xvf tarballs/$TARNAME -C src
done